/*
Generated by Mix
Sat Apr 30 20:27:46 2016 GMT-0400
*/

var Election = {
	"abi": "[{\"constant\":false,\"inputs\":[{\"name\":\"v\",\"type\":\"uint256\"}],\"name\":\"vote\",\"outputs\":[],\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"getVote\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"isActive\",\"outputs\":[{\"name\":\"\",\"type\":\"bool\"}],\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"getVoteTallies\",\"outputs\":[],\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"registerCandidate\",\"outputs\":[],\"type\":\"function\"},{\"inputs\":[{\"name\":\"v\",\"type\":\"uint256\"}],\"type\":\"constructor\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"name\":\"choice_id\",\"type\":\"uint256\"}],\"name\":\"Vote\",\"type\":\"event\"}]",
	"codeHex": "0x6060604052604051602080610181833981016040528080519060200190919050505b806000600050819055505b506101468061003b6000396000f360606040526000357c0100000000000000000000000000000000000000000000000000000000900480630121b93f146100655780630242f3511461007d57806322f3e2d4146100a0578063ca656e5a146100c3578063f7e0079e146100d257610063565b005b61007b6004808035906020019091905050610118565b005b61008a6004805050610134565b6040518082815260200191505060405180910390f35b6100ad600480505061010a565b6040518082815260200191505060405180910390f35b6100d060048050506100e4565b005b6100df60048050506100e1565b005b5b565b6000600090505b600360005054811015610106575b80806001019150506100eb565b5b50565b600060019050610115565b90565b61012061010a565b1561013057806000600050819055505b5b50565b60006000600050549050610143565b9056",
	"name": "Election"
}

