/*
Generated by Mix
Sun May 1 22:09:21 2016 GMT-0400
*/

var Election = {
	"abi": "[{\"constant\":false,\"inputs\":[{\"name\":\"v\",\"type\":\"uint256\"}],\"name\":\"vote\",\"outputs\":[],\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"getVote\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"isActive\",\"outputs\":[{\"name\":\"\",\"type\":\"bool\"}],\"type\":\"function\"},{\"constant\":false,\"inputs\":[{\"name\":\"voter_address\",\"type\":\"address\"}],\"name\":\"registerVoter\",\"outputs\":[],\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"getVoteTallies\",\"outputs\":[],\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"registerCandidate\",\"outputs\":[],\"type\":\"function\"},{\"inputs\":[{\"name\":\"v\",\"type\":\"uint256\"}],\"type\":\"constructor\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"name\":\"choice_id\",\"type\":\"uint256\"}],\"name\":\"Vote\",\"type\":\"event\"}]",
	"codeHex": "0x60606040526040516020806101ae833981016040528080519060200190919050505b806000600050819055505b506101738061003b6000396000f360606040523615610074576000357c0100000000000000000000000000000000000000000000000000000000900480630121b93f146100765780630242f3511461008e57806322f3e2d4146100b157806338db6dd3146100d4578063ca656e5a146100ec578063f7e0079e146100fb57610074565b005b61008c6004808035906020019091905050610157565b005b61009b600480505061010a565b6040518082815260200191505060405180910390f35b6100be600480505061011c565b6040518082815260200191505060405180910390f35b6100ea6004808035906020019091905050610153565b005b6100f9600480505061012a565b005b6101086004805050610150565b005b60006000600050549050610119565b90565b600060019050610127565b90565b6000600090505b60036000505481101561014c575b8080600101915050610131565b5b50565b5b565b5b50565b61015f61011c565b1561016f57806000600050819055505b5b5056",
	"name": "Election"
}

